With the help of [Numpy Documentation] https://numpy.org/devdocs/user/absolute_beginners.html

In [94]:
import numpy as np

Create a numpy array

In [95]:
a=np.array([1,2,3,5])
print(a)

[1 2 3 5]


In [96]:
b=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Access different elements of Numpy

In [97]:
print(a[0])

1


In [98]:
print(b[0][0])

1


In [99]:
print(b[1][2])

7


Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [100]:
np.zeros(3)

array([0., 0., 0.])

An array filled with 1’s

In [101]:
np.ones(4)

array([1., 1., 1., 1.])

create an empty array. The function empty creates an array whose initial content is random and depends on the state of the memory.
The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [102]:
np.empty(2)

array([1.13092843e-311, 0.00000000e+000])

In [103]:
np.arange(4)

array([0, 1, 2, 3])

In [104]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

create an array with values that are spaced linearly in a specified interval

In [106]:
np.linspace(0,10,num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

you can explicitly specify which data type you want using the dtype keyword.

In [107]:
np.ones(11,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Adding, removing, and sorting elements

In [108]:
arr1=np.array([2,3,4,8,1])
arr1.sort()
arr1

array([1, 2, 3, 4, 8])

Concatenation of 2 arrays

In [109]:
arr2=np.array([5,7,9])

In [110]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 8, 5, 7, 9])

ndarray.ndim will tell you the number of axes, or dimensions, of the array

In [111]:
b.ndim

2

To find the total number of elements in the array

In [112]:
b.size

12

In [113]:
b.shape

(3, 4)

And to find the shape of your array

Reshape an Array

In [114]:
a.reshape(2,2)

array([[1, 2],
       [3, 5]])

How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [115]:
arr1.shape

(5,)

In [116]:
newarr1=arr1[np.newaxis,:]

In [117]:
newarr1.shape

(1, 5)

In [118]:
newarr1

array([[1, 2, 3, 4, 8]])

Indexing and Slicing 

In [119]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
b[2][3]

12

In [121]:
b[0:1]

array([[1, 2, 3, 4]])

In [122]:
b[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
b[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
b[2:]

array([[ 9, 10, 11, 12]])

In [125]:
print(b[b>4])

[ 5  6  7  8  9 10 11 12]


some functions 

In [126]:
b.max()

12

In [127]:
b.min()

1

In [128]:
c=a+b
c

array([[ 2,  4,  6,  9],
       [ 6,  8, 10, 13],
       [10, 12, 14, 17]])

In [129]:
diff=c-b
diff

array([[1, 2, 3, 5],
       [1, 2, 3, 5],
       [1, 2, 3, 5]])

In [130]:
diff.sum()

33

In [136]:
matrix=np.array([[1,2],[3,4]])

In [137]:
matrix

array([[1, 2],
       [3, 4]])

Generate Random numbers

In [138]:
from numpy.random import default_rng

In [141]:
rng=default_rng()
vals =rng.standard_normal(10)

In [142]:
vals

array([ 0.22826697,  0.78146954, -0.44035976, -1.11880025, -2.33559846,
        0.09580313,  1.89642733, -0.19685675, -0.21034965, -0.28245953])

In [143]:
morevals =rng.standard_normal(10)
morevals

array([-0.84533593,  0.83917677,  1.39664026, -0.52778216, -0.37829986,
       -0.56103828,  0.36538576,  1.12646339, -0.70437603, -0.33591223])

Get Unique Values

In [144]:
unique=np.unique(vals)

In [145]:
unique

array([-2.33559846, -1.11880025, -0.44035976, -0.28245953, -0.21034965,
       -0.19685675,  0.09580313,  0.22826697,  0.78146954,  1.89642733])

In [147]:
newarr=np.array([1,2,3,5,1,5,2,7,8])

In [148]:
unique=np.unique(newarr)

In [149]:
unique

array([1, 2, 3, 5, 7, 8])

Transposing a Matrix

In [150]:
transpose=np.transpose(matrix)

In [151]:
transpose

array([[1, 3],
       [2, 4]])

Reversing an array

In [152]:
rev=np.flip(newarr)

In [153]:
rev

array([8, 7, 2, 5, 1, 5, 3, 2, 1])

Worked on Numpy exercise

In [157]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

What is the average value of the second column (to two decimal places)

In [159]:
avg=np.average(random_integers)
avg

235261.82

How to create a boolean array?

In [167]:
bool=np.full((3,3),True)

In [168]:
bool

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [169]:
#Q. Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [173]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [174]:
#Q. Replace all odd numbers in arr with -1
arr[arr%2==1]=-1

In [175]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [176]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
#Q. Replace all odd numbers in arr with -1 without changing arr

np.where((arr%2==1),-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [184]:
#Q. Convert a 1D array to a 2D array with 2 rows

arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

I hope this helps 