In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4]

In [3]:
my_array=np.array(list1)

In [5]:
my_array  #one dimensional array

array([1, 2, 3, 4])

In [6]:
my_mat=np.matrix([[1,2,3],[3,4,5],[6,7,8]])

In [7]:
my_mat

matrix([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros((5,5)) # to create 5X5 array of 0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((2,3))  # to create array of 1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,5,10)   #create an array with start and stop and no of members

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)  # to create identity matrix"

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5) # 1 d array of random numbers

array([0.84852884, 0.07686844, 0.2652351 , 0.93795485, 0.25808956])

In [16]:
np.random.rand(5,5) # 2 d array of randome numbers

array([[0.03236138, 0.55507176, 0.83463047, 0.222016  , 0.41212034],
       [0.12105382, 0.50953681, 0.08784786, 0.71615733, 0.26023778],
       [0.16385339, 0.59828677, 0.07569036, 0.64146856, 0.6717602 ],
       [0.88064014, 0.02539806, 0.47068909, 0.48922201, 0.39111032],
       [0.32413061, 0.01528294, 0.07406123, 0.71767463, 0.06151983]])

In [18]:
np.random.randn(4,4)   # random numbers from random distribution

array([[ 2.21073732e-01, -8.54556838e-01,  1.37710219e+00,
         8.67123442e-01],
       [-2.16141614e+00,  1.06877733e+00, -5.64933267e-02,
         1.31066533e-01],
       [-4.09544518e-04, -7.12306212e-01, -7.02194299e-01,
         1.28799621e+00],
       [-1.57028349e+00, -9.07170701e-01,  1.25442530e+00,
         2.57525427e-01]])

In [20]:
np.random.randint(0,100)  #random integer between 1-99

77

In [23]:
randomarr=np.random.randint(0,100,25) #10 random integers between 1-99

In [30]:
randomarr.reshape(5,5)

array([[ 8, 59, 64, 22,  3],
       [63, 99, 87, 11, 15],
       [32, 94, 59, 83, 12],
       [45, 28, 19, 58, 14],
       [88, 38, 86, 48, 11]])

In [25]:
randomarr

array([ 8, 59, 64, 22,  3, 63, 99, 87, 11, 15, 32, 94, 59, 83, 12, 45, 28,
       19, 58, 14, 88, 38, 86, 48, 11])

In [27]:
randomarr.max()  #get the maximum number in the array

99

In [28]:
randomarr.min() #get the minimum number in the array

3

In [31]:
randomarr.shape

(25,)

In [34]:
randomarr.dtype

dtype('int32')

In [35]:
arr=np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[4] #get value at index 4

4

In [40]:
arr[1:4] #indexing and slicing

array([1, 2, 3])

In [44]:
arr[1:3]=55   #convert elements from index 1-3 as 55 

In [45]:
arr

array([ 0, 55, 55,  3,  4,  5,  6,  7,  8,  9, 10])

### Create an array of 10 zeros 

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create an array of 10 ones

In [50]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Create an array of 10 fives

In [63]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create an array of the integers from 10 to 50

In [64]:
arr=np.arange(10,51)

In [65]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of all the even integers from 10 to 50

In [68]:
arr=np.arange(10,51,2)

In [69]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 matrix with values ranging from 0 to 8

In [81]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a 3x3 identity matrix

In [82]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Use NumPy to generate a random number between 0 and 1

In [84]:
np.random.randint(0,1)

0

### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [85]:
np.random.randn(25)

array([ 0.44711432, -0.21598184, -1.35664025, -0.39848803, -1.45061303,
        1.49708858,  0.57091036, -0.70323029, -0.54217199,  2.20941605,
        1.89505943, -1.68352775,  0.08358196,  0.40119467, -0.36487185,
       -0.61515056, -1.2392173 , -0.05813636,  0.79361871,  0.73219066,
        1.29354232,  1.85004765,  0.49910526,  0.88544005,  0.15453606])

In [88]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [90]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [91]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [93]:
mat[3,4]

20

In [108]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [110]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [111]:
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Get the sum of all the values in mat

In [112]:
mat.sum()

325

### Get the standard deviation of the values in mat

In [113]:
mat.std()

7.211102550927978

### Get the sum of all the columns in matrix

In [115]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])